# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths: # make sure this action only runs when specific file extensions have been added/modified
      - "**.js"
      - "**.jsx"

jobs:
  ts-checks-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checks
      - uses: owen-6936/ts-checks@v1.0.0
      - run: run lint
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout main 
          git checkout ${{ github.head_ref }}
      - name: Eslint Changeset Step
        uses: esrimo/gh-action-eslint-changeset@v1
        id: eslint-changeset
        with:
          main-branch: "main"
          file-extension: "ts"   
      - name: jest-check
        uses: soomo/jest-check@0.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEST_FOLDER: ${{ github.workspace }}/spec
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm lint
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
